/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerProyec;
import Model.Proyecto;
import Model.Usuario;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Riarb
 */
public class elementosComplementarios extends javax.swing.JPanel {
    boolean esc,bar,tech,ramp;
    ControllerProyec controller;
    Usuario usuarioActual;
    Proyecto proyecto;
    double presupuestoTotal;
    /**
     * Creates new form elementosComplementarios
     */
    public elementosComplementarios(Proyecto proyec, Usuario usuario,double presupuesto) {
        initComponents();
        esc = true;
        bar= true;
        tech= true;
        ramp=true;
        controller=new ControllerProyec(this);
        usuarioActual = usuario;
        proyecto = proyec;
        presupuestoTotal= presupuesto;
        try {
            controller.llenarBoxMateriales(materialBox1);
            controller.llenarBoxMateriales(materialBox2);
            controller.llenarBoxMateriales(materialBox3);
            controller.llenarBoxMateriales(materialBox4);
        } catch (SQLException ex) {
            Logger.getLogger(fundamentosYcimentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentElementos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        deshabilitarButtom1 = new javax.swing.JPanel();
        deshabilitarLabel1 = new javax.swing.JLabel();
        habilitarButtom1 = new javax.swing.JPanel();
        habilitarLabel1 = new javax.swing.JLabel();
        materialBox1 = new javax.swing.JComboBox<>();
        precio1 = new javax.swing.JPanel();
        precio1Label = new javax.swing.JLabel();
        habilitarButtom2 = new javax.swing.JPanel();
        habilitarLabel2 = new javax.swing.JLabel();
        deshabilitarButtom2 = new javax.swing.JPanel();
        deshabilitarLabel2 = new javax.swing.JLabel();
        precioPanel2 = new javax.swing.JPanel();
        precioLabel2 = new javax.swing.JLabel();
        materialBox2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        rampaLabel = new javax.swing.JLabel();
        techoLabel = new javax.swing.JLabel();
        escaleraLabel = new javax.swing.JLabel();
        barandasLabel = new javax.swing.JLabel();
        materialBox3 = new javax.swing.JComboBox<>();
        materialBox4 = new javax.swing.JComboBox<>();
        precio3 = new javax.swing.JPanel();
        precioLabel3 = new javax.swing.JLabel();
        precio4 = new javax.swing.JPanel();
        precioLabel4 = new javax.swing.JLabel();
        habilitarButtom3 = new javax.swing.JPanel();
        habilitarLabel3 = new javax.swing.JLabel();
        deshabilitarButtom3 = new javax.swing.JPanel();
        deshabilitarLabel3 = new javax.swing.JLabel();
        habilitarButtom4 = new javax.swing.JPanel();
        habilitarLabel4 = new javax.swing.JLabel();
        deshabilitarButtom4 = new javax.swing.JPanel();
        deshabilitarLabel4 = new javax.swing.JLabel();
        guardarButtom = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        contentElementos.setBackground(new java.awt.Color(0, 153, 153));
        contentElementos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        tituloLabel.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("ELEMENTOS COMPLEMENTARIOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(36, 36, 36))
        );

        contentElementos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 17, 618, -1));

        deshabilitarButtom1.setBackground(new java.awt.Color(0, 102, 102));
        deshabilitarButtom1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deshabilitarButtom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshabilitarButtom1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deshabilitarButtom1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deshabilitarButtom1MouseExited(evt);
            }
        });

        deshabilitarLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        deshabilitarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        deshabilitarLabel1.setText("Deshabilitar");

        javax.swing.GroupLayout deshabilitarButtom1Layout = new javax.swing.GroupLayout(deshabilitarButtom1);
        deshabilitarButtom1.setLayout(deshabilitarButtom1Layout);
        deshabilitarButtom1Layout.setHorizontalGroup(
            deshabilitarButtom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deshabilitarButtom1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deshabilitarLabel1)
                .addGap(36, 36, 36))
        );
        deshabilitarButtom1Layout.setVerticalGroup(
            deshabilitarButtom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deshabilitarButtom1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deshabilitarLabel1)
                .addContainerGap())
        );

        contentElementos.add(deshabilitarButtom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 65, -1));

        habilitarButtom1.setBackground(new java.awt.Color(0, 102, 102));
        habilitarButtom1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habilitarButtom1.setEnabled(false);
        habilitarButtom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habilitarButtom1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                habilitarButtom1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                habilitarButtom1MouseExited(evt);
            }
        });

        habilitarLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        habilitarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        habilitarLabel1.setText("  Habilitar");
        habilitarLabel1.setEnabled(false);

        javax.swing.GroupLayout habilitarButtom1Layout = new javax.swing.GroupLayout(habilitarButtom1);
        habilitarButtom1.setLayout(habilitarButtom1Layout);
        habilitarButtom1Layout.setHorizontalGroup(
            habilitarButtom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        habilitarButtom1Layout.setVerticalGroup(
            habilitarButtom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        contentElementos.add(habilitarButtom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        materialBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material" }));
        materialBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialBox1ActionPerformed(evt);
            }
        });
        contentElementos.add(materialBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        precio1Label.setText("Precio");

        javax.swing.GroupLayout precio1Layout = new javax.swing.GroupLayout(precio1);
        precio1.setLayout(precio1Layout);
        precio1Layout.setHorizontalGroup(
            precio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(precio1Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        precio1Layout.setVerticalGroup(
            precio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, precio1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(precio1Label))
        );

        contentElementos.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        habilitarButtom2.setBackground(new java.awt.Color(0, 102, 102));
        habilitarButtom2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habilitarButtom2.setEnabled(false);
        habilitarButtom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habilitarButtom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                habilitarButtom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                habilitarButtom2MouseExited(evt);
            }
        });

        habilitarLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        habilitarLabel2.setForeground(new java.awt.Color(255, 255, 255));
        habilitarLabel2.setText("Habilitar");
        habilitarLabel2.setEnabled(false);

        javax.swing.GroupLayout habilitarButtom2Layout = new javax.swing.GroupLayout(habilitarButtom2);
        habilitarButtom2.setLayout(habilitarButtom2Layout);
        habilitarButtom2Layout.setHorizontalGroup(
            habilitarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        habilitarButtom2Layout.setVerticalGroup(
            habilitarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentElementos.add(habilitarButtom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 71, -1));

        deshabilitarButtom2.setBackground(new java.awt.Color(0, 102, 102));
        deshabilitarButtom2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deshabilitarButtom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshabilitarButtom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deshabilitarButtom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deshabilitarButtom2MouseExited(evt);
            }
        });

        deshabilitarLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        deshabilitarLabel2.setForeground(new java.awt.Color(255, 255, 255));
        deshabilitarLabel2.setText("Deshabilitar");

        javax.swing.GroupLayout deshabilitarButtom2Layout = new javax.swing.GroupLayout(deshabilitarButtom2);
        deshabilitarButtom2.setLayout(deshabilitarButtom2Layout);
        deshabilitarButtom2Layout.setHorizontalGroup(
            deshabilitarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deshabilitarButtom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deshabilitarLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deshabilitarButtom2Layout.setVerticalGroup(
            deshabilitarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deshabilitarButtom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deshabilitarLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentElementos.add(deshabilitarButtom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 71, -1));

        precioLabel2.setText("Precio");

        javax.swing.GroupLayout precioPanel2Layout = new javax.swing.GroupLayout(precioPanel2);
        precioPanel2.setLayout(precioPanel2Layout);
        precioPanel2Layout.setHorizontalGroup(
            precioPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, precioPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(precioLabel2)
                .addGap(29, 29, 29))
        );
        precioPanel2Layout.setVerticalGroup(
            precioPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precioPanel2Layout.createSequentialGroup()
                .addComponent(precioLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        contentElementos.add(precioPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 341, 49, 22));

        materialBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material" }));
        contentElementos.add(materialBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 341, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        contentElementos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 618, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        contentElementos.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 406, 612, 19));

        rampaLabel.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        rampaLabel.setForeground(new java.awt.Color(242, 242, 242));
        rampaLabel.setText("Rampas");
        contentElementos.add(rampaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 140, -1));

        techoLabel.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        techoLabel.setForeground(new java.awt.Color(242, 242, 242));
        techoLabel.setText("Techos");
        contentElementos.add(techoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        escaleraLabel.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        escaleraLabel.setForeground(new java.awt.Color(242, 242, 242));
        escaleraLabel.setText("Escalera");
        contentElementos.add(escaleraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 149, 120, -1));

        barandasLabel.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        barandasLabel.setForeground(new java.awt.Color(242, 242, 242));
        barandasLabel.setText("Barandas");
        contentElementos.add(barandasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        materialBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material" }));
        materialBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialBox3ActionPerformed(evt);
            }
        });
        contentElementos.add(materialBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        materialBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material" }));
        materialBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialBox4ActionPerformed(evt);
            }
        });
        contentElementos.add(materialBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        precioLabel3.setText("Precio");

        javax.swing.GroupLayout precio3Layout = new javax.swing.GroupLayout(precio3);
        precio3.setLayout(precio3Layout);
        precio3Layout.setHorizontalGroup(
            precio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, precio3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(precioLabel3)
                .addContainerGap())
        );
        precio3Layout.setVerticalGroup(
            precio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precio3Layout.createSequentialGroup()
                .addComponent(precioLabel3)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        contentElementos.add(precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 22));

        precioLabel4.setText("Precio");

        javax.swing.GroupLayout precio4Layout = new javax.swing.GroupLayout(precio4);
        precio4.setLayout(precio4Layout);
        precio4Layout.setHorizontalGroup(
            precio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, precio4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(precioLabel4)
                .addContainerGap())
        );
        precio4Layout.setVerticalGroup(
            precio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precio4Layout.createSequentialGroup()
                .addComponent(precioLabel4)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        contentElementos.add(precio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        habilitarButtom3.setBackground(new java.awt.Color(0, 102, 102));
        habilitarButtom3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habilitarButtom3.setEnabled(false);
        habilitarButtom3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habilitarButtom3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                habilitarButtom3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                habilitarButtom3MouseExited(evt);
            }
        });

        habilitarLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        habilitarLabel3.setForeground(new java.awt.Color(255, 255, 255));
        habilitarLabel3.setText("Habilitar");
        habilitarLabel3.setEnabled(false);

        javax.swing.GroupLayout habilitarButtom3Layout = new javax.swing.GroupLayout(habilitarButtom3);
        habilitarButtom3.setLayout(habilitarButtom3Layout);
        habilitarButtom3Layout.setHorizontalGroup(
            habilitarButtom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        habilitarButtom3Layout.setVerticalGroup(
            habilitarButtom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentElementos.add(habilitarButtom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 70, -1));

        deshabilitarButtom3.setBackground(new java.awt.Color(0, 102, 102));
        deshabilitarButtom3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deshabilitarButtom3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshabilitarButtom3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deshabilitarButtom3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deshabilitarButtom3MouseExited(evt);
            }
        });

        deshabilitarLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        deshabilitarLabel3.setForeground(new java.awt.Color(255, 255, 255));
        deshabilitarLabel3.setText("Deshabilitar");

        javax.swing.GroupLayout deshabilitarButtom3Layout = new javax.swing.GroupLayout(deshabilitarButtom3);
        deshabilitarButtom3.setLayout(deshabilitarButtom3Layout);
        deshabilitarButtom3Layout.setHorizontalGroup(
            deshabilitarButtom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deshabilitarButtom3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deshabilitarLabel3)
                .addGap(36, 36, 36))
        );
        deshabilitarButtom3Layout.setVerticalGroup(
            deshabilitarButtom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deshabilitarButtom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deshabilitarLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentElementos.add(deshabilitarButtom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 70, -1));

        habilitarButtom4.setBackground(new java.awt.Color(0, 102, 102));
        habilitarButtom4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habilitarButtom4.setEnabled(false);
        habilitarButtom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habilitarButtom4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                habilitarButtom4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                habilitarButtom4MouseExited(evt);
            }
        });

        habilitarLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        habilitarLabel4.setForeground(new java.awt.Color(255, 255, 255));
        habilitarLabel4.setText("Habilitar");
        habilitarLabel4.setEnabled(false);

        javax.swing.GroupLayout habilitarButtom4Layout = new javax.swing.GroupLayout(habilitarButtom4);
        habilitarButtom4.setLayout(habilitarButtom4Layout);
        habilitarButtom4Layout.setHorizontalGroup(
            habilitarButtom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        habilitarButtom4Layout.setVerticalGroup(
            habilitarButtom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(habilitarButtom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(habilitarLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentElementos.add(habilitarButtom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        deshabilitarButtom4.setBackground(new java.awt.Color(0, 102, 102));
        deshabilitarButtom4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deshabilitarButtom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshabilitarButtom4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deshabilitarButtom4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deshabilitarButtom4MouseExited(evt);
            }
        });

        deshabilitarLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        deshabilitarLabel4.setForeground(new java.awt.Color(255, 255, 255));
        deshabilitarLabel4.setText("Deshabilitar");

        javax.swing.GroupLayout deshabilitarButtom4Layout = new javax.swing.GroupLayout(deshabilitarButtom4);
        deshabilitarButtom4.setLayout(deshabilitarButtom4Layout);
        deshabilitarButtom4Layout.setHorizontalGroup(
            deshabilitarButtom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deshabilitarButtom4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deshabilitarLabel4)
                .addContainerGap())
        );
        deshabilitarButtom4Layout.setVerticalGroup(
            deshabilitarButtom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deshabilitarButtom4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deshabilitarLabel4)
                .addContainerGap())
        );

        contentElementos.add(deshabilitarButtom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        guardarButtom.setBackground(new java.awt.Color(0, 102, 102));
        guardarButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarButtomMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GUARDAR");

        javax.swing.GroupLayout guardarButtomLayout = new javax.swing.GroupLayout(guardarButtom);
        guardarButtom.setLayout(guardarButtomLayout);
        guardarButtomLayout.setHorizontalGroup(
            guardarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guardarButtomLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
        );
        guardarButtomLayout.setVerticalGroup(
            guardarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardarButtomLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        contentElementos.add(guardarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentElementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentElementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deshabilitarButtom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom1MouseClicked
        habilitarButtom1.setEnabled(true);
        habilitarLabel1.setEnabled(true);
        deshabilitarButtom1.setEnabled(false);
        deshabilitarLabel1.setEnabled(false);
        escaleraLabel.setEnabled(false);
        precio1Label.setEnabled(false);
        precio1.setEnabled(false);
        materialBox1.setEnabled(false);
        esc= false;
        
    }//GEN-LAST:event_deshabilitarButtom1MouseClicked

    private void deshabilitarButtom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom1MouseEntered
        deshabilitarButtom1.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_deshabilitarButtom1MouseEntered

    private void deshabilitarButtom1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom1MouseExited
        deshabilitarButtom1.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_deshabilitarButtom1MouseExited

    private void habilitarButtom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom1MouseClicked
        habilitarButtom1.setEnabled(false);
        habilitarLabel1.setEnabled(false);
        deshabilitarButtom1.setEnabled(true);
        deshabilitarLabel1.setEnabled(true);
        escaleraLabel.setEnabled(true);
        precio1Label.setEnabled(true);
        precio1.setEnabled(true);
        materialBox1.setEnabled(true);
        esc = true;
    }//GEN-LAST:event_habilitarButtom1MouseClicked

    private void habilitarButtom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom1MouseEntered
        habilitarButtom1.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_habilitarButtom1MouseEntered

    private void habilitarButtom1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom1MouseExited
        habilitarButtom1.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_habilitarButtom1MouseExited

    private void materialBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialBox1ActionPerformed

    private void habilitarButtom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom2MouseClicked
        habilitarButtom2.setEnabled(false);
        habilitarLabel2.setEnabled(false);
        deshabilitarButtom2.setEnabled(true);
        deshabilitarLabel2.setEnabled(true);
        barandasLabel.setEnabled(true);
        precioLabel2.setEnabled(true);
        precioPanel2.setEnabled(true);
        materialBox2.setEnabled(true);
        bar = true;
    }//GEN-LAST:event_habilitarButtom2MouseClicked

    private void habilitarButtom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom2MouseEntered
        habilitarButtom2.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_habilitarButtom2MouseEntered

    private void habilitarButtom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom2MouseExited
        habilitarButtom2.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_habilitarButtom2MouseExited

    private void deshabilitarButtom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom2MouseClicked
        habilitarButtom2.setEnabled(true);
        habilitarLabel2.setEnabled(true);
        deshabilitarButtom2.setEnabled(false);
        deshabilitarLabel2.setEnabled(false);
        barandasLabel.setEnabled(false);
        precioLabel2.setEnabled(false);
        precioPanel2.setEnabled(false);
        materialBox2.setEnabled(false);
        bar= false;
    }//GEN-LAST:event_deshabilitarButtom2MouseClicked

    private void deshabilitarButtom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom2MouseEntered
        deshabilitarButtom2.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_deshabilitarButtom2MouseEntered

    private void deshabilitarButtom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom2MouseExited
        deshabilitarButtom2.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_deshabilitarButtom2MouseExited

    private void materialBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialBox3ActionPerformed

    private void materialBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialBox4ActionPerformed

    private void habilitarButtom3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom3MouseClicked
        habilitarButtom3.setEnabled(false);
        habilitarLabel3.setEnabled(false);
        deshabilitarButtom3.setEnabled(true);
        deshabilitarLabel3.setEnabled(true);
        rampaLabel.setEnabled(true);
        precioLabel3.setEnabled(true);
        precio3.setEnabled(true);
        materialBox3.setEnabled(true);
        ramp=true;
    }//GEN-LAST:event_habilitarButtom3MouseClicked

    private void habilitarButtom3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom3MouseEntered
        habilitarButtom3.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_habilitarButtom3MouseEntered

    private void habilitarButtom3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom3MouseExited
        habilitarButtom3.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_habilitarButtom3MouseExited

    private void deshabilitarButtom3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom3MouseClicked
        habilitarButtom3.setEnabled(true);
        habilitarLabel3.setEnabled(true);
        deshabilitarButtom3.setEnabled(false);
        deshabilitarLabel3.setEnabled(false);
        rampaLabel.setEnabled(false);
        precioLabel3.setEnabled(false);
        precio3.setEnabled(false);
        materialBox3.setEnabled(false);
        ramp=false;
    }//GEN-LAST:event_deshabilitarButtom3MouseClicked

    private void deshabilitarButtom3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom3MouseEntered
        deshabilitarButtom3.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_deshabilitarButtom3MouseEntered

    private void deshabilitarButtom3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom3MouseExited
        deshabilitarButtom3.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_deshabilitarButtom3MouseExited

    private void habilitarButtom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom4MouseClicked
        habilitarButtom4.setEnabled(false);
        habilitarLabel4.setEnabled(false);
        deshabilitarButtom4.setEnabled(true);
        deshabilitarLabel4.setEnabled(true);
        techoLabel.setEnabled(true);
        precio4.setEnabled(true);
        precioLabel4.setEnabled(true);
        materialBox4.setEnabled(true);
        tech= true;
    }//GEN-LAST:event_habilitarButtom4MouseClicked

    private void habilitarButtom4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom4MouseEntered
        habilitarButtom4.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_habilitarButtom4MouseEntered

    private void habilitarButtom4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarButtom4MouseExited
        habilitarButtom4.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_habilitarButtom4MouseExited

    private void deshabilitarButtom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom4MouseClicked
        habilitarButtom4.setEnabled(true);
        habilitarLabel4.setEnabled(true);
        deshabilitarButtom4.setEnabled(false);
        deshabilitarLabel4.setEnabled(false);
        techoLabel.setEnabled(false);
        precioLabel4.setEnabled(false);
        precio4.setEnabled(false);
        materialBox4.setEnabled(false);
        tech = false;
    }//GEN-LAST:event_deshabilitarButtom4MouseClicked

    private void deshabilitarButtom4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom4MouseEntered
        deshabilitarButtom4.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_deshabilitarButtom4MouseEntered

    private void deshabilitarButtom4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshabilitarButtom4MouseExited
       deshabilitarButtom4.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_deshabilitarButtom4MouseExited

    private void guardarButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseClicked
        if(esc && materialBox1.getSelectedItem().equals("Material")){
            JOptionPane.showMessageDialog(null, "La parte llamada 'Escalera' esta habilitada y no has escogido un material para ella.");
        }else if(bar && materialBox2.getSelectedItem().equals("Material")){
            JOptionPane.showMessageDialog(null, "La parte llamada 'Barandas' esta habilitada y no has escogido un material para ella.");
        }else if(ramp && materialBox3.getSelectedItem().equals("Material")){
            JOptionPane.showMessageDialog(null, "La parte llamada 'Rampas' esta habilitada y no has escogido un material para ella.");
        }else if(tech && materialBox4.getSelectedItem().equals("Material")){
            JOptionPane.showMessageDialog(null, "La parte llamada 'Techos' esta habilitada y no has escogido un material para ella.");
        }else{
            try{
                if(esc && !materialBox1.getSelectedItem().equals("Material")){
                    controller.guardarMateriales(proyecto,materialBox1,"UPDATE partes SET Escalera = ? WHERE id_partes = ?");
//                    presupuestoTotal = presupuestoTotal + Double.parseDouble(precio1Label.getText());
                }
                if(bar && !materialBox2.getSelectedItem().equals("Material")){
                    controller.guardarMateriales(proyecto,materialBox3,"UPDATE partes SET Barandas = ? WHERE id_partes = ?");
//                    presupuestoTotal = presupuestoTotal + Double.parseDouble(precioLabel2.getText());
                }
                if(ramp && !materialBox3.getSelectedItem().equals("Material")){
                    controller.guardarMateriales(proyecto,materialBox2,"UPDATE partes SET Rampas = ? WHERE id_partes = ?");
//                    presupuestoTotal = presupuestoTotal + Double.parseDouble(precioLabel3.getText());
                }
                if(tech && !materialBox4.getSelectedItem().equals("Material")){
                    controller.guardarMateriales(proyecto,materialBox4,"UPDATE partes SET Techos = ? WHERE id_partes = ?");
//                    presupuestoTotal = presupuestoTotal + Double.parseDouble(precioLabel4.getText());
                }
            }catch (SQLException ex) {
                Logger.getLogger(fundamentosYcimentacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrarEscogido p = new mostrarEscogido(proyecto,usuarioActual,presupuestoTotal);
            p.setSize(613,530);
            p.setLocation(0,0);
            contentElementos.removeAll();
            contentElementos.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
            contentElementos.revalidate();
            contentElementos.repaint();
        }
    }//GEN-LAST:event_guardarButtomMouseClicked

    private void guardarButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseEntered
        guardarButtom.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_guardarButtomMouseEntered

    private void guardarButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseExited
        guardarButtom.setBackground(new Color(0,102,102));

    }//GEN-LAST:event_guardarButtomMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barandasLabel;
    private javax.swing.JPanel contentElementos;
    private javax.swing.JPanel deshabilitarButtom1;
    private javax.swing.JPanel deshabilitarButtom2;
    private javax.swing.JPanel deshabilitarButtom3;
    private javax.swing.JPanel deshabilitarButtom4;
    private javax.swing.JLabel deshabilitarLabel1;
    private javax.swing.JLabel deshabilitarLabel2;
    private javax.swing.JLabel deshabilitarLabel3;
    private javax.swing.JLabel deshabilitarLabel4;
    private javax.swing.JLabel escaleraLabel;
    private javax.swing.JPanel guardarButtom;
    private javax.swing.JPanel habilitarButtom1;
    private javax.swing.JPanel habilitarButtom2;
    private javax.swing.JPanel habilitarButtom3;
    private javax.swing.JPanel habilitarButtom4;
    private javax.swing.JLabel habilitarLabel1;
    private javax.swing.JLabel habilitarLabel2;
    private javax.swing.JLabel habilitarLabel3;
    private javax.swing.JLabel habilitarLabel4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> materialBox1;
    private javax.swing.JComboBox<String> materialBox2;
    private javax.swing.JComboBox<String> materialBox3;
    private javax.swing.JComboBox<String> materialBox4;
    private javax.swing.JPanel precio1;
    private javax.swing.JLabel precio1Label;
    private javax.swing.JPanel precio3;
    private javax.swing.JPanel precio4;
    private javax.swing.JLabel precioLabel2;
    private javax.swing.JLabel precioLabel3;
    private javax.swing.JLabel precioLabel4;
    private javax.swing.JPanel precioPanel2;
    private javax.swing.JLabel rampaLabel;
    private javax.swing.JLabel techoLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
