/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerProyec;
import Model.Proyecto;
import Model.Usuario;
import java.awt.*;
import javax.swing.*;



/**
 *
 * @author Riarb
 */
public class mostrarEscogido extends javax.swing.JPanel {
    ControllerProyec controller;
    Usuario usuarioActual;
    Proyecto proyecto;
    double presupuestoTotal;
    /**
     * Creates new form mostrarEscogido
     */
    public mostrarEscogido(Proyecto proyec, Usuario usuario,double presupuesto) {
        initComponents();
        controller=new ControllerProyec(this);
        usuarioActual = usuario;
        proyecto = proyec;
        presupuestoTotal= presupuesto;
        nombreDato.setText(proyec.getNombreProyecto());
        presupuestoDato.setText(String.valueOf(proyec.getPresupuesto()));
        autorDato.setText(usuario.getNombreUsuario()+" "+usuario.getApellidoUsuario()+" ("+usuario.getUsuario()+").");
        costoDato.setText(String.valueOf(presupuesto));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        contentVista = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entrarButtom = new javax.swing.JPanel();
        entrarLabel = new javax.swing.JLabel();
        mostrarDatosButtom = new javax.swing.JPanel();
        entrarLabel1 = new javax.swing.JLabel();
        autorDato = new javax.swing.JLabel();
        nombreDato = new javax.swing.JLabel();
        costoDato = new javax.swing.JLabel();
        presupuestoDato = new javax.swing.JLabel();
        entrarButtom2 = new javax.swing.JPanel();
        entrarLabel2 = new javax.swing.JLabel();

        contentVista.setBackground(new java.awt.Color(0, 153, 153));
        contentVista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        tituloLabel.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("VISTA PREVIA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        contentVista.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 613, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del proyecto:");
        contentVista.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Autor: ");
        contentVista.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Costo total: ");
        contentVista.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Presupuesto: ");
        contentVista.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        entrarButtom.setBackground(new java.awt.Color(0, 102, 102));
        entrarButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarButtomMouseExited(evt);
            }
        });

        entrarLabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        entrarLabel.setForeground(new java.awt.Color(255, 255, 255));
        entrarLabel.setText("VOLVER");

        javax.swing.GroupLayout entrarButtomLayout = new javax.swing.GroupLayout(entrarButtom);
        entrarButtom.setLayout(entrarButtomLayout);
        entrarButtomLayout.setHorizontalGroup(
            entrarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entrarButtomLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(entrarLabel)
                .addGap(50, 50, 50))
        );
        entrarButtomLayout.setVerticalGroup(
            entrarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entrarButtomLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(entrarLabel)
                .addContainerGap())
        );

        contentVista.add(entrarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        mostrarDatosButtom.setBackground(new java.awt.Color(0, 102, 102));
        mostrarDatosButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarDatosButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarDatosButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarDatosButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarDatosButtomMouseExited(evt);
            }
        });

        entrarLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        entrarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        entrarLabel1.setText("MOSTRAR DATOS");

        javax.swing.GroupLayout mostrarDatosButtomLayout = new javax.swing.GroupLayout(mostrarDatosButtom);
        mostrarDatosButtom.setLayout(mostrarDatosButtomLayout);
        mostrarDatosButtomLayout.setHorizontalGroup(
            mostrarDatosButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarDatosButtomLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(entrarLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        mostrarDatosButtomLayout.setVerticalGroup(
            mostrarDatosButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarDatosButtomLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(entrarLabel1)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        contentVista.add(mostrarDatosButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 230, 230));

        String aux;
        aux="Pepe";
        autorDato.setText(aux);
        contentVista.add(autorDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 30));

        nombreDato.setText("Kiosco 69");
        contentVista.add(nombreDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 30));

        costoDato.setText("4500$");
        contentVista.add(costoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 30));

        presupuestoDato.setText("5000$");
        contentVista.add(presupuestoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 30));

        entrarButtom2.setBackground(new java.awt.Color(0, 102, 102));
        entrarButtom2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarButtom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarButtom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarButtom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarButtom2MouseExited(evt);
            }
        });

        entrarLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        entrarLabel2.setForeground(new java.awt.Color(255, 255, 255));
        entrarLabel2.setText("GUARDAR");

        javax.swing.GroupLayout entrarButtom2Layout = new javax.swing.GroupLayout(entrarButtom2);
        entrarButtom2.setLayout(entrarButtom2Layout);
        entrarButtom2Layout.setHorizontalGroup(
            entrarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entrarButtom2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(entrarLabel2)
                .addGap(50, 50, 50))
        );
        entrarButtom2Layout.setVerticalGroup(
            entrarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entrarButtom2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(entrarLabel2)
                .addContainerGap())
        );

        contentVista.add(entrarButtom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVista, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entrarButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtomMouseClicked
        elementosComplementarios p = new elementosComplementarios(proyecto,usuarioActual,presupuestoTotal);
        p.setSize(613,530);
        p.setLocation(0,0);
        contentVista.removeAll();
        contentVista.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        contentVista.revalidate();
        contentVista.repaint();

    }//GEN-LAST:event_entrarButtomMouseClicked

    private void entrarButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtomMouseEntered
        entrarButtom.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_entrarButtomMouseEntered

    private void entrarButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtomMouseExited
        entrarButtom.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_entrarButtomMouseExited

    private void mostrarDatosButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosButtomMouseClicked
        vistaPrevia vista = new vistaPrevia();
        vista.setVisible(true);
    }//GEN-LAST:event_mostrarDatosButtomMouseClicked

    private void mostrarDatosButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosButtomMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarDatosButtomMouseEntered

    private void mostrarDatosButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosButtomMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarDatosButtomMouseExited

    private void entrarButtom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtom2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtom2MouseClicked

    private void entrarButtom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtom2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtom2MouseEntered

    private void entrarButtom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtom2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtom2MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorDato;
    private javax.swing.JPanel contentVista;
    private javax.swing.JLabel costoDato;
    private javax.swing.JPanel entrarButtom;
    private javax.swing.JPanel entrarButtom2;
    private javax.swing.JLabel entrarLabel;
    private javax.swing.JLabel entrarLabel1;
    private javax.swing.JLabel entrarLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel mostrarDatosButtom;
    private javax.swing.JLabel nombreDato;
    private javax.swing.JLabel presupuestoDato;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
