/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerPDF;
import Controller.ControllerProyec;
import Model.Material;
import Model.Proyecto;
import Model.Usuario;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Riarb
 */
public class verProyecto extends javax.swing.JPanel {
    Usuario usuarioActual;
    Proyecto proyecto;
    List<Material> escogido;
    /**
     * Creates new form verProyecto
     */
    public verProyecto(Usuario usuario, Proyecto proyec) {
        initComponents();
        ControllerProyec controller = new ControllerProyec(this);
        usuarioActual = usuario;
        proyecto = proyec;
        nombreDato.setText(proyec.getNombreProyecto());
        presupuestoDato.setText(String.valueOf(proyec.getPresupuesto()));
        autorDato.setText(usuario.getNombreUsuario()+" "+usuario.getApellidoUsuario()+" ("+usuario.getUsuario()+").");
        if("Dolares ($)".equals(usuario.getMonedaUsuario())){
            costoDato.setText(String.valueOf(proyec.getPresupuestoTotal())+" $");
        }else if("Bolivares (Bs)".equals(usuario.getMonedaUsuario())){
            costoDato.setText(String.valueOf(proyec.getPresupuestoTotal())+" Bs");
        }
        escogido = new ArrayList<>();
        try {
            controller.llenarListaEscogido(escogido, proyecto);
        } catch (SQLException ex) {
            Logger.getLogger(verProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentVista = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mostrarDatosButtom = new javax.swing.JPanel();
        entrarLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        autorDato = new javax.swing.JLabel();
        nombreDato = new javax.swing.JLabel();
        costoDato = new javax.swing.JLabel();
        presupuestoDato = new javax.swing.JLabel();
        imprimirButtom = new javax.swing.JPanel();
        ingresarLabel = new javax.swing.JLabel();
        volverButtom = new javax.swing.JPanel();
        ingresarLabel1 = new javax.swing.JLabel();
        ingresarButtom2 = new javax.swing.JPanel();
        ingresarLabel2 = new javax.swing.JLabel();
        ingresarButtom3 = new javax.swing.JPanel();
        ingresarLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        publicoDato = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SustentabilidadDato = new javax.swing.JLabel();
        actividadDato = new javax.swing.JLabel();
        costoDato3 = new javax.swing.JLabel();

        contentVista.setBackground(new java.awt.Color(0, 153, 153));
        contentVista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        tituloLabel.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("VER PROYECTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        contentVista.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 613, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del proyecto:");
        contentVista.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Autor: ");
        contentVista.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sustentabilidad:");
        contentVista.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Presupuesto: ");
        contentVista.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        mostrarDatosButtom.setBackground(new java.awt.Color(0, 102, 102));
        mostrarDatosButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarDatosButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarDatosButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarDatosButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarDatosButtomMouseExited(evt);
            }
        });

        entrarLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        entrarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        entrarLabel1.setText("MOSTRAR DATOS");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo blanco.png"))); // NOI18N

        javax.swing.GroupLayout mostrarDatosButtomLayout = new javax.swing.GroupLayout(mostrarDatosButtom);
        mostrarDatosButtom.setLayout(mostrarDatosButtomLayout);
        mostrarDatosButtomLayout.setHorizontalGroup(
            mostrarDatosButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarDatosButtomLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(entrarLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(mostrarDatosButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrarDatosButtomLayout.createSequentialGroup()
                    .addContainerGap(28, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        mostrarDatosButtomLayout.setVerticalGroup(
            mostrarDatosButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarDatosButtomLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(entrarLabel1)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(mostrarDatosButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrarDatosButtomLayout.createSequentialGroup()
                    .addContainerGap(35, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        contentVista.add(mostrarDatosButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 230, 190));

        String aux;
        aux="Pepe";
        autorDato.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        autorDato.setForeground(new java.awt.Color(242, 242, 242));
        autorDato.setText(aux);
        contentVista.add(autorDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 30));

        nombreDato.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        nombreDato.setForeground(new java.awt.Color(242, 242, 242));
        nombreDato.setText("Kiosco 69");
        contentVista.add(nombreDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 30));

        costoDato.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        costoDato.setForeground(new java.awt.Color(242, 242, 242));
        costoDato.setText("4500$");
        contentVista.add(costoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 30));

        presupuestoDato.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        presupuestoDato.setForeground(new java.awt.Color(242, 242, 242));
        presupuestoDato.setText("5000$");
        contentVista.add(presupuestoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 30));

        imprimirButtom.setBackground(new java.awt.Color(0, 102, 102));
        imprimirButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimirButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprimirButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imprimirButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imprimirButtomMouseExited(evt);
            }
        });

        ingresarLabel.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ingresarLabel.setForeground(new java.awt.Color(255, 255, 255));
        ingresarLabel.setText("IMPRIMIR");

        javax.swing.GroupLayout imprimirButtomLayout = new javax.swing.GroupLayout(imprimirButtom);
        imprimirButtom.setLayout(imprimirButtomLayout);
        imprimirButtomLayout.setHorizontalGroup(
            imprimirButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imprimirButtomLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(ingresarLabel)
                .addGap(34, 34, 34))
        );
        imprimirButtomLayout.setVerticalGroup(
            imprimirButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimirButtomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ingresarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentVista.add(imprimirButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, 60));

        volverButtom.setBackground(new java.awt.Color(0, 102, 102));
        volverButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverButtomMouseExited(evt);
            }
        });

        ingresarLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ingresarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ingresarLabel1.setText("VOLVER");

        javax.swing.GroupLayout volverButtomLayout = new javax.swing.GroupLayout(volverButtom);
        volverButtom.setLayout(volverButtomLayout);
        volverButtomLayout.setHorizontalGroup(
            volverButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volverButtomLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(ingresarLabel1)
                .addGap(33, 33, 33))
        );
        volverButtomLayout.setVerticalGroup(
            volverButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volverButtomLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(ingresarLabel1)
                .addGap(15, 15, 15))
        );

        contentVista.add(volverButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        ingresarButtom2.setBackground(new java.awt.Color(0, 102, 102));
        ingresarButtom2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarButtom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarButtom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarButtom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarButtom2MouseExited(evt);
            }
        });

        ingresarLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ingresarLabel2.setForeground(new java.awt.Color(255, 255, 255));
        ingresarLabel2.setText("VOLVER");

        javax.swing.GroupLayout ingresarButtom2Layout = new javax.swing.GroupLayout(ingresarButtom2);
        ingresarButtom2.setLayout(ingresarButtom2Layout);
        ingresarButtom2Layout.setHorizontalGroup(
            ingresarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarButtom2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(ingresarLabel2)
                .addGap(33, 33, 33))
        );
        ingresarButtom2Layout.setVerticalGroup(
            ingresarButtom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarButtom2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(ingresarLabel2)
                .addGap(15, 15, 15))
        );

        contentVista.add(ingresarButtom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        ingresarButtom3.setBackground(new java.awt.Color(0, 102, 102));
        ingresarButtom3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarButtom3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarButtom3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarButtom3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarButtom3MouseExited(evt);
            }
        });

        ingresarLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ingresarLabel3.setForeground(new java.awt.Color(255, 255, 255));
        ingresarLabel3.setText("VOLVER");

        javax.swing.GroupLayout ingresarButtom3Layout = new javax.swing.GroupLayout(ingresarButtom3);
        ingresarButtom3.setLayout(ingresarButtom3Layout);
        ingresarButtom3Layout.setHorizontalGroup(
            ingresarButtom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarButtom3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(ingresarLabel3)
                .addGap(33, 33, 33))
        );
        ingresarButtom3Layout.setVerticalGroup(
            ingresarButtom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarButtom3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(ingresarLabel3)
                .addGap(15, 15, 15))
        );

        contentVista.add(ingresarButtom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Actividad:");
        contentVista.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        publicoDato.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        publicoDato.setForeground(new java.awt.Color(255, 255, 255));
        publicoDato.setText("Publico:");
        contentVista.add(publicoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Costo total: ");
        contentVista.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        SustentabilidadDato.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        SustentabilidadDato.setForeground(new java.awt.Color(242, 242, 242));
        SustentabilidadDato.setText("4500$");
        contentVista.add(SustentabilidadDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, 30));

        actividadDato.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        actividadDato.setForeground(new java.awt.Color(242, 242, 242));
        actividadDato.setText("4500$");
        contentVista.add(actividadDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, 30));

        costoDato3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        costoDato3.setForeground(new java.awt.Color(242, 242, 242));
        costoDato3.setText("4500$");
        contentVista.add(costoDato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVista, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarDatosButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosButtomMouseClicked
        try {
            buscarProyecto vista = new buscarProyecto(proyecto);
            vista.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(verProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostrarDatosButtomMouseClicked

    private void mostrarDatosButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosButtomMouseEntered
        mostrarDatosButtom.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_mostrarDatosButtomMouseEntered

    private void mostrarDatosButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarDatosButtomMouseExited
        mostrarDatosButtom.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_mostrarDatosButtomMouseExited

    private void imprimirButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirButtomMouseClicked
        String nombre = JOptionPane.showInputDialog(null, "Ingrese como desea nombrar al pdf:", "Entrada de Nombre", JOptionPane.QUESTION_MESSAGE);
        if(nombre!=null){
            ControllerPDF pdf = new ControllerPDF(usuarioActual,proyecto,escogido,nombre+".pdf");
            pdf.imprimirProyecto();
        }
        
    }//GEN-LAST:event_imprimirButtomMouseClicked

    private void imprimirButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirButtomMouseEntered
        imprimirButtom.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_imprimirButtomMouseEntered

    private void imprimirButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirButtomMouseExited
        imprimirButtom.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_imprimirButtomMouseExited

    private void volverButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtomMouseClicked
        verProyectoMenu p3 = new verProyectoMenu(usuarioActual);
        p3.setSize(613,530);
        p3.setLocation(0,0);
        contentVista.removeAll();
        contentVista.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        contentVista.revalidate();
        contentVista.repaint();
    }//GEN-LAST:event_volverButtomMouseClicked

    private void volverButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtomMouseEntered
        volverButtom.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_volverButtomMouseEntered

    private void volverButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtomMouseExited
        volverButtom.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_volverButtomMouseExited

    private void ingresarButtom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButtom2MouseClicked
        ingresarButtom2.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_ingresarButtom2MouseClicked

    private void ingresarButtom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButtom2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarButtom2MouseEntered

    private void ingresarButtom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButtom2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarButtom2MouseExited

    private void ingresarButtom3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButtom3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarButtom3MouseClicked

    private void ingresarButtom3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButtom3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarButtom3MouseEntered

    private void ingresarButtom3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButtom3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarButtom3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SustentabilidadDato;
    private javax.swing.JLabel actividadDato;
    private javax.swing.JLabel autorDato;
    private javax.swing.JPanel contentVista;
    private javax.swing.JLabel costoDato;
    private javax.swing.JLabel costoDato3;
    private javax.swing.JLabel entrarLabel1;
    private javax.swing.JPanel imprimirButtom;
    private javax.swing.JPanel ingresarButtom2;
    private javax.swing.JPanel ingresarButtom3;
    private javax.swing.JLabel ingresarLabel;
    private javax.swing.JLabel ingresarLabel1;
    private javax.swing.JLabel ingresarLabel2;
    private javax.swing.JLabel ingresarLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mostrarDatosButtom;
    private javax.swing.JLabel nombreDato;
    private javax.swing.JLabel presupuestoDato;
    private javax.swing.JLabel publicoDato;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel volverButtom;
    // End of variables declaration//GEN-END:variables
}
